name: Run Cypress Test Suite
on: push

jobs:
  run-tests:
    name: Run Cypress tests
    runs-on: ubuntu-latest
    container:
      image: composer:latest
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Running composer install
        run: composer install
      - name: Running e2e tests
        run: .//Users/viktoradamski/GoIT_projects/docker-project integration